### ISSUE TITLE
line normalizer class from my branch

### ISSUE THREAD

**Issue by purarue** [karlicoss/bleanser#18]
By the way, I pretty much exclusively use bleanser to remove redundant backups (dont really modify the data at all), through this class I wrote:

https://github.com/seanbreckenridge/bleanser/blob/master/src/bleanser_sean/line_normalizer.py

I'm not exactly sure if its the best way to do so, but might be useful to have here as its an easy way for someone to get started writing bleanser modules if all they want to do is remove redundant backups

for examples see:

https://github.com/seanbreckenridge/bleanser/blob/master/src/bleanser_sean/modules/chess.py

https://github.com/seanbreckenridge/bleanser/blob/master/src/bleanser_sean/modules/zsh.py

If I need to do more complex stuff, I can always override some of the helper classes, e.g. see:

https://github.com/seanbreckenridge/bleanser/blob/master/src/bleanser_sean/modules/discord.py

could be renamed or changed if you think there are things that could be improved, I was writing this only half understanding the bleanser code here, but I remember being pretty happy with the class, and its worked for me for new modules for over a year

**Comment by karlicoss** [comment]
I checked your modules -- I see the logic, a bit different from modules I wrote, but it makes sense as well!

I feel like I wrote about it somewhere, but can't find anything except this crappy braindump :sweat_smile: https://beepb00p.xyz/exobrain/projects/bleanser.html#pttrnfhndlngnknwndtsrcs

Basically the idea is there are two ways of normalizing export files to figure out whether they are equivalent:

- extract "useful" fields with some sort of parser (like you're doing by hooking into HPI) and compare the results
- or cleanup fields that were verified to be "useless", perhaps apply some very minimal normalisation and compare the results

Kinda nice actually that we have examples of both, e.g. for smscalls
- https://github.com/seanbreckenridge/bleanser/blob/master/src/bleanser_sean/modules/smscalls.py
- https://github.com/karlicoss/bleanser/blob/master/src/bleanser/modules/smscalls.py

The 'extract' method will generally result in better cleanup quality.
However the downside is that if you didn't handle some data in the parser or the data source has more raw data which you aren't aware of yet, you're going to start deleting potentially useful export files -- and I'm quite paranoid about that :sweat_smile: 
So for that reason I mainly preferred the 'cleanup' approach. Another reason is just trying to keep it simple, and dependency on HPI kinda complicates things (although at the same time makes a lot of sense to benefit from HPI to cleanup!)

Ideally I think bleanser modules should do both. E.g. you specify both `cleanup` function (like in existing modules), and something like `extract` function (like `handle_json`/`parse_file` do in your modules).
Then bleanser could call both at the same time, and this would help verify the correctness of cleanup as well. 
E.g. you have two exports `A` and `B` -- if according to `cleanup` they are identical, and according to `extract` they aren't then it means cleanup is removing too much stuff. 
If according to cleanup they are different, and according to extract they are the same, that means you could perhaps cleanup more data (or extract some data which you haven't noticed before)
If only either of `cleanup` or `extract` are specified it would still work as before.

"old" version of bleanser used to kinda do that (without hooking into HPI though), but I dropped the extract bit while was doing a rewrite https://github.com/karlicoss/bleanser/blob/master/old/reddit.py

What do you think? 

-----

> By the way, I pretty much exclusively use bleanser to remove redundant backups (dont really modify the data at all)

Ah -- I guess it looks confusing -- bleanser actually doesn't modify the original data at all, if you see any `del` from json or dropping stuff from the databases -- it's always operating on copies.

**Comment by purarue** [comment]
> bleanser actually doesn't modify the original data at all, if you see any del from json or dropping stuff from the databases -- it's always operating on copies

was not obvious to me, I thought it was deleting useless data. good to know

> or cleanup fields that were verified to be "useless", perhaps apply some very minimal normalisation and compare the results

> However the downside is that if you didn't handle some data in the parser or the data source has more raw data which you aren't aware of yet, you're going to start deleting potentially useful export files

Ahh... this did not click for me beforehand, but it makes a lot of sense!

I think I had too much trouble originally following the base normalizer -> json normalizer -> modules using it, so I rewrote a bit of the code you have in `modules/json_new.py`

That way each module can override `cleanup`, and receive some XML element or a JSON blob, and it can remove stuff thats not useful for comparing

got it.

Will try and rewrite one of my modules using the cleanup approach, and write some docs for bleanser (you may need to review though, not sure if I totally grasp everything, but could probably at least give someone a starting point)

> dependency on HPI kinda complicates things

Agreed, theres a trade off there. I think its worth it for some of my modules -- if its  just JSON objects I just process those without using any functions from HPI

>  E.g. you have two exports A and B -- if according to cleanup they are identical, and according to extract they aren't then it means cleanup is removing too much stuff.

Yeah, sounds like a cool idea, might be able to notify you that your know your underlying data format has changed. but probably something a user has to opt-into, is somewhat complicated as is.

**Comment by karlicoss** [comment]
Btw, I think `LineNormaliser` is kinda doing what (pretty confusingly named) ["binary"](https://github.com/karlicoss/bleanser/blob/master/src/bleanser/modules/binary.py) module does -- it just basically treats a file as is (except for sorting the lines).
But binary doesn't provide any way to hook into it yeah (`do_cleanup` here just returns the 'input' path https://github.com/karlicoss/bleanser/blob/9682fbb30add04e6578936296dc8206217c37402/src/bleanser/core/processor.py#L43 )

So yeah I think it makes a lot of sense to have a core normaliser that just allows you to do whatever you want with path and emit a custom 'key' (like you're doing with an iterable)! 
I guess it's a bit of a shame it has to be so complicated at the moment (with all the unpacking/tmp paths etc), so perhaps could think a bit about refactoring as well so there is less duplication

**Comment by karlicoss** [comment]
> I think I had too much trouble originally following the base normalizer -> json normalizer -> modules using it, so I rewrote a bit of the code you have in modules/json_new.py

Yeah, totally get it -- it kind of grown organically so even I get a bit confused after not touching it for a while.Kinda grateful for myself adding a lot of tests at the time I wrote most of it :sweat_smile: 

Also while the algorithm for actual cleanup is efficient, also kinda nuts https://github.com/karlicoss/bleanser/blob/9682fbb30add04e6578936296dc8206217c37402/src/bleanser/core/processor.py#L353  (I did have trouble with disk space use while processing thousands of files at first due to operating on copies)

> (you may need to review though, not sure if I totally grasp everything, but could probably at least give someone a starting point

Of course, really appreciate it! Feel free to ping me on zulip. I'll try to dig out all the notes I have on it in case it brings more context

**Comment by purarue** [comment]
>  I guess it's a bit of a shame it has to be so complicated at the moment (with all the unpacking/tmp paths etc), so perhaps could think a bit about refactoring as well so there is less duplication

[refactoring out the function to create the unique tempfile](https://github.com/seanbreckenridge/bleanser/blob/70caa0b45769e3aa8a5680607143512c74d809e4/src/bleanser_sean/line_normalizer.py#L18-L28) like I do would be nice

could also add some helper functions that are named nicer that hide the creating the unique tempfile/sorting to compare, Im pretty happy with the `Iterator[Any]`, converting to a string and then replacing newlines (that way the downstream subclass can just return *anything*, and it gets stringified and put on one line in the file to compare) with this pattern (could replace the `re.sub` with something better though)

https://github.com/seanbreckenridge/bleanser/blob/70caa0b45769e3aa8a5680607143512c74d809e4/src/bleanser_sean/line_normalizer.py#L48-L66

yeah, I think with some examples/docstrings would be more obvious, will PR some when I rewrite some of my modules a bit

**Comment by purarue** [comment]
added stuff in #22
